<template>
  <div class="privacy-policy">
    <div class="title">Privacy Policy</div>
    <p>We do not store any data on our servers. All data generated by the app is stored directly in the user's device.</p>
  </div>
</template>

<script>
export default {

}
</script>

<style>
.privacy-policy {
  margin-left: 1rem;
  margin-top: 1rem;
}
</style>